# 第五次课作业

In [1]:
import pandas as pd
import numpy as np

（1）读取数据。读取之前作业保存的“酒店数据1.xlsx”

In [4]:
df = pd.read_excel("酒店数据1.xlsx",index_col=0)

（2）将“类型”和“名字”设置为层次化索引，并交换索引的位置。然后将层次化索引取消。

In [7]:
df = df.set_index(["类型","名字"])
df

                                                       城市    地区  \
类型   名字
浪漫情侣 香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)    香港    东区
商务出行 香港碧荟酒店(The BEACON)                                香港   油尖旺
浪漫情侣 香港湾仔帝盛酒店(Dorsett Wanchai)                         香港    湾仔
     如心艾朗酒店(L‘hotel elan)                              香港    观塘
     香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)            香港    湾仔
...                                                    ..   ...
地铁周边 香港金泉酒店                                            香港  其他地区
     香港天天宾馆(TIN TIN GUEST HOUSE)                       香港   油尖旺
海滨风光 香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)  香港    荃湾
     香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)  香港    荃湾
地铁周边 香港花盈酒店(家庭旅馆)(Bloomy Hotel)                        香港   油尖旺

                                                                         地点  \
类型   名字
浪漫情侣 香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)                铜锣湾永兴街8号
商务出行 香港碧荟酒店(The BEACON)                                          九龙旺角洗衣街88号
浪漫情侣 香港湾仔帝盛酒店(Dorsett Wanchai)                                皇后大道东387-397号
     如心艾朗酒店(L‘hotel elan)                                          观塘创业街38号
     香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)                   铜锣湾边宁顿街13-15号
...                                                                     ...
地铁周边 香港金泉酒店                                            香港旺角弥敦道607号新兴大厦1407室
     香港天天宾馆(TIN TIN GUEST HOUSE)                         旺角弥敦道607号新兴大厦1517A
海滨风光 香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)              荃湾 杨屋道8号
     香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)              荃湾 杨屋道8号
地铁周边 香港花盈酒店(家庭旅馆)(Bloomy Hotel)                         尖沙咀弥敦道87号华源大厦9字楼C2室

                                                             评分   评分人数   价格
类型   名字
浪漫情侣 香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)    4.500000  12708  693
商务出行 香港碧荟酒店(The BEACON)                                4.700000    328  747
浪漫情侣 香港湾仔帝盛酒店(Dorsett Wanchai)                         4.400000   5014  693
     如心艾朗酒店(L‘hotel elan)                              4.600000   3427  581
     香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)            4.500000   1938  869
...                                                         ...    ...  ...
地铁周边 香港金泉酒店                                            4.282973     16  245
     香港天天宾馆(TIN TIN GUEST HOUSE)                       3.200000     16  227
海滨风光 香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)  4.500000  45462  709
     香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre)  4.500000  45463  709
地铁周边 香港花盈酒店(家庭旅馆)(Bloomy Hotel)                        4.000000    273  256

[396 rows x 6 columns]

In [9]:
df = df.swaplevel("名字","类型")
df

                                                       城市    地区  \
名字                                               类型
香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)   浪漫情侣  香港    东区
香港碧荟酒店(The BEACON)                               商务出行  香港   油尖旺
香港湾仔帝盛酒店(Dorsett Wanchai)                        浪漫情侣  香港    湾仔
如心艾朗酒店(L‘hotel elan)                             浪漫情侣  香港    观塘
香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)           浪漫情侣  香港    湾仔
...                                                    ..   ...
香港金泉酒店                                           地铁周边  香港  其他地区
香港天天宾馆(TIN TIN GUEST HOUSE)                      地铁周边  香港   油尖旺
香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre) 海滨风光  香港    荃湾
                                                 海滨风光  香港    荃湾
香港花盈酒店(家庭旅馆)(Bloomy Hotel)                       地铁周边  香港   油尖旺

                                                                         地点  \
名字                                               类型
香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)   浪漫情侣              铜锣湾永兴街8号
香港碧荟酒店(The BEACON)                               商务出行            九龙旺角洗衣街88号
香港湾仔帝盛酒店(Dorsett Wanchai)                        浪漫情侣         皇后大道东387-397号
如心艾朗酒店(L‘hotel elan)                             浪漫情侣              观塘创业街38号
香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)           浪漫情侣         铜锣湾边宁顿街13-15号
...                                                                     ...
香港金泉酒店                                           地铁周边  香港旺角弥敦道607号新兴大厦1407室
香港天天宾馆(TIN TIN GUEST HOUSE)                      地铁周边    旺角弥敦道607号新兴大厦1517A
香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre) 海滨风光              荃湾 杨屋道8号
                                                 海滨风光              荃湾 杨屋道8号
香港花盈酒店(家庭旅馆)(Bloomy Hotel)                       地铁周边   尖沙咀弥敦道87号华源大厦9字楼C2室

                                                             评分   评分人数   价格
名字                                               类型
香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay)   浪漫情侣  4.500000  12708  693
香港碧荟酒店(The BEACON)                               商务出行  4.700000    328  747
香港湾仔帝盛酒店(Dorsett Wanchai)                        浪漫情侣  4.400000   5014  693
如心艾朗酒店(L‘hotel elan)                             浪漫情侣  4.600000   3427  581
香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus)           浪漫情侣  4.500000   1938  869
...                                                         ...    ...  ...
香港金泉酒店                                           地铁周边  4.282973     16  245
香港天天宾馆(TIN TIN GUEST HOUSE)                      地铁周边  3.200000     16  227
香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre) 海滨风光  4.500000  45462  709
                                                 海滨风光  4.500000  45463  709
香港花盈酒店(家庭旅馆)(Bloomy Hotel)                       地铁周边  4.000000    273  256

[396 rows x 6 columns]

In [11]:
df = df.reset_index()
df

,名字,类型,城市,地区,地点,评分,评分人数,价格
0,香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay),浪漫情侣,香港,东区,铜锣湾永兴街8号,4.500000,12708,693
1,香港碧荟酒店(The BEACON),商务出行,香港,油尖旺,九龙旺角洗衣街88号,4.700000,328,747
2,香港湾仔帝盛酒店(Dorsett Wanchai),浪漫情侣,香港,湾仔,皇后大道东387-397号,4.400000,5014,693
3,如心艾朗酒店(L‘hotel elan),浪漫情侣,香港,观塘,观塘创业街38号,4.600000,3427,581
4,香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus),浪漫情侣,香港,湾仔,铜锣湾边宁顿街13-15号,4.500000,1938,869
...,...,...,...,...,...,...,...,...
391,香港金泉酒店,地铁周边,香港,其他地区,香港旺角弥敦道607号新兴大厦1407室,4.282973,16,245
392,香港天天宾馆(TIN TIN GUEST HOUSE),地铁周边,香港,油尖旺,旺角弥敦道607号新兴大厦1517A,3.200000,16,227
393,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.500000,45462,709
394,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.500000,45463,709
395,香港花盈酒店(家庭旅馆)(Bloomy Hotel),地铁周边,香港,油尖旺,尖沙咀弥敦道87号华源大厦9字楼C2室,4.000000,273,256

（3）将数据集转置，获取转制后的index和columns。

In [14]:
df = df.T
df.columns.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395], dtype=int64)

In [15]:
df.index.values

array(['名字', '类型', '城市', '地区', '地点', '评分', '评分人数', '价格'], dtype=object)

（4）用Groupby方法来计算每个地区的评分人数的总和以及均值。

In [17]:
df=df.T
df["评分人数"].groupby(df["地区"]).sum()

地区
东区       56643
中西区      59682
九龙城      49855
元朗        1200
其他地区     16831
南区       12867
屯门        7324
沙田       39622
油尖旺     422574
深水埗区        16
湾仔      107344
离岛       60359
罗湖区         24
荃湾      114610
葵青       11544
观塘       19137
Name: 评分人数, dtype: object

In [18]:
df["评分人数"].groupby(df["地区"]).mean()

地区
东区       3540.187500
中西区      1808.545455
九龙城      2374.047619
元朗       1200.000000
其他地区      300.553571
南区       2573.400000
屯门       3662.000000
沙田       9905.500000
油尖旺      2284.183784
深水埗区       16.000000
湾仔       2618.146341
离岛       5487.181818
罗湖区        24.000000
荃湾      16372.857143
葵青       2308.800000
观塘       2733.857143
Name: 评分人数, dtype: float64

（5）用Grouby方法计算每个类型的平均价格，最高价和最低价。

In [21]:
df['价格'].groupby(df["类型"]).mean()
df['价格'].groupby(df["类型"]).max()
df['价格'].groupby(df["类型"]).min()

              价格_x   价格_y
类型
交通方便    421.000000    421
亲子酒店    745.400000   1686
休闲度假   1151.300000   4443
其他类型    269.300000    881
印象好     297.000000    297
商务出行   1045.153846   3159
地铁周边    374.139535   2640
大学周边    325.000000    325
客栈      397.666667    553
干净卫生    185.000000    185
民宿      258.500000    506
浪漫情侣    608.573529   1908
海滨风光   1543.573770  12926
火车站周边   968.000000    968
环境不错    357.666667    484
老板热情    385.000000    385
酒店公寓   1182.000000   2309
青年旅舍    189.250000    348

（6）数据离散化，按照价格将酒店分为3个等级,0-500为C，500-1000为B,大于1000为A，列名设置为“价格等级”。

In [23]:
df['价格等级'] = pd.cut(df["价格"],[0,500,1000,100000],labels=['C','B','A'])
df

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级
0,香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay),浪漫情侣,香港,东区,铜锣湾永兴街8号,4.5,12708,693,B
1,香港碧荟酒店(The BEACON),商务出行,香港,油尖旺,九龙旺角洗衣街88号,4.7,328,747,B
2,香港湾仔帝盛酒店(Dorsett Wanchai),浪漫情侣,香港,湾仔,皇后大道东387-397号,4.4,5014,693,B
3,如心艾朗酒店(L‘hotel elan),浪漫情侣,香港,观塘,观塘创业街38号,4.6,3427,581,B
4,香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus),浪漫情侣,香港,湾仔,铜锣湾边宁顿街13-15号,4.5,1938,869,B
...,...,...,...,...,...,...,...,...,...
391,香港金泉酒店,地铁周边,香港,其他地区,香港旺角弥敦道607号新兴大厦1407室,4.282973,16,245,C
392,香港天天宾馆(TIN TIN GUEST HOUSE),地铁周边,香港,油尖旺,旺角弥敦道607号新兴大厦1517A,3.2,16,227,C
393,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45462,709,B
394,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45463,709,B
395,香港花盈酒店(家庭旅馆)(Bloomy Hotel),地铁周边,香港,油尖旺,尖沙咀弥敦道87号华源大厦9字楼C2室,4.0,273,256,C

（7）获取评分均值最高和最低的地区的数据，分别使用append和concat方法将获取的两个数据集合并。

In [30]:
group = df["评分"].groupby(df["地区"]).mean()
group = group.sort_values()
df1 = df[df["地区"]==group.index[0]]
df1.append(df[df["地区"]==group.index[-1]])

C:\Users\2075221336\AppData\Local\Temp\ipykernel_69724\3188349884.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df[df["地区"]==group.index[-1]])

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级
42,香港荃湾旭逸酒店(Hotel Ease Tsuen Wan),浪漫情侣,香港,葵青,葵涌圳边街15-19号,4.4,598,394,C
199,香港永倫800酒店(WINLAND800HOTEL),其他类型,香港,葵青,新界青衣路一号,3.4,3098,196,C
200,香港青逸酒店(Rambler Oasis Hotel),浪漫情侣,香港,葵青,青衣路1号,4.0,3091,349,C
213,香港华逸酒店(Rambler Garden Hotel),浪漫情侣,香港,葵青,青衣 青衣路1号,4.0,3031,349,C
215,香港文化旅馆-翠雅山房(Hong Kong Heritage Lodge),浪漫情侣,香港,葵青,香港九龙青山道800号,4.4,1726,423,C
24,香港黄金海岸酒店(Hong Kong Gold Coast Hotel),海滨风光,香港,屯门,屯门 黄金海岸青山公路1号,4.7,6326,696,B
168,香港屯门贝尔特酒店(pentahotel Hong Kong Tuen Mun),浪漫情侣,香港,屯门,新界屯门震寰路六号,4.5,998,582,B

In [31]:
df1 = df[df["地区"]==group.index[0]]
df2 = df[df["地区"]==group.index[-1]]
pd.concat([df1,df2],axis=0)

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级
42,香港荃湾旭逸酒店(Hotel Ease Tsuen Wan),浪漫情侣,香港,葵青,葵涌圳边街15-19号,4.4,598,394,C
199,香港永倫800酒店(WINLAND800HOTEL),其他类型,香港,葵青,新界青衣路一号,3.4,3098,196,C
200,香港青逸酒店(Rambler Oasis Hotel),浪漫情侣,香港,葵青,青衣路1号,4.0,3091,349,C
213,香港华逸酒店(Rambler Garden Hotel),浪漫情侣,香港,葵青,青衣 青衣路1号,4.0,3031,349,C
215,香港文化旅馆-翠雅山房(Hong Kong Heritage Lodge),浪漫情侣,香港,葵青,香港九龙青山道800号,4.4,1726,423,C
24,香港黄金海岸酒店(Hong Kong Gold Coast Hotel),海滨风光,香港,屯门,屯门 黄金海岸青山公路1号,4.7,6326,696,B
168,香港屯门贝尔特酒店(pentahotel Hong Kong Tuen Mun),浪漫情侣,香港,屯门,新界屯门震寰路六号,4.5,998,582,B

（8）数据离散化，按照评分人数将酒店平均分为3个等级，三个等级的酒店数量尽量保持一致。评分人数最多的为A，最少的为C。列名设置为“热门等级”。

In [49]:
df["热门等级"] = pd.cut(df['评分人数'],[0,200,2000,1000000],labels=["C","B","A"])
df

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级,热门等级
0,香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay),浪漫情侣,香港,东区,铜锣湾永兴街8号,4.5,12708,693,B,A
1,香港碧荟酒店(The BEACON),商务出行,香港,油尖旺,九龙旺角洗衣街88号,4.7,328,747,B,B
2,香港湾仔帝盛酒店(Dorsett Wanchai),浪漫情侣,香港,湾仔,皇后大道东387-397号,4.4,5014,693,B,A
3,如心艾朗酒店(L‘hotel elan),浪漫情侣,香港,观塘,观塘创业街38号,4.6,3427,581,B,A
4,香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus),浪漫情侣,香港,湾仔,铜锣湾边宁顿街13-15号,4.5,1938,869,B,B
...,...,...,...,...,...,...,...,...,...,...
391,香港金泉酒店,地铁周边,香港,其他地区,香港旺角弥敦道607号新兴大厦1407室,4.282973,16,245,C,C
392,香港天天宾馆(TIN TIN GUEST HOUSE),地铁周边,香港,油尖旺,旺角弥敦道607号新兴大厦1517A,3.2,16,227,C,C
393,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45462,709,B,A
394,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45463,709,B,A
395,香港花盈酒店(家庭旅馆)(Bloomy Hotel),地铁周边,香港,油尖旺,尖沙咀弥敦道87号华源大厦9字楼C2室,4.0,273,256,C,B

（9）选出评分人数为A，价格也为A的酒店数据，计算其平均评分。

In [54]:
df[(df["热门等级"]=="A") & (df["价格等级"]=="A")]['评分'].mean()

4.6599999999999975

（10）取价格最高的5个酒店的数据，使用stack和unstack方法实现dataframe和Series之间的转换。

In [57]:
d = df.sort_values(by="价格",ascending=False)[:5]
s = d.stack()
s

116  名字               香港四季酒店(Four Seasons Hotel Hong Kong)
     类型                                               海滨风光
     城市                                                 香港
     地区                                                中西区
     地点                                           中环 金融街8号
     评分                                                4.8
     评分人数                                             3461
     价格                                              12926
     价格等级                                                A
     热门等级                                                A
115  名字      香港置地文华东方酒店(The Landmark Mandarin Oriental HK)
     类型                                               休闲度假
     城市                                                 香港
     地区                                                中西区
     地点                                    中环 皇后大道中15号置地广场
     评分                                                4.8
     评分人数                                             1285
     价格                                               4443
     价格等级                                                A
     热门等级                                                B
88   名字                                奕居(The Upper House)
     类型                                               海滨风光
     城市                                                 香港
     地区                                                中西区
     地点                                         金钟道88号太古广场
     评分                                                4.8
     评分人数                                             1369
     价格                                               4356
     价格等级                                                A
     热门等级                                                B
82   名字                    香港半岛酒店(The Peninsula Hong Kong)
     类型                                               海滨风光
     城市                                                 香港
     地区                                                油尖旺
     地点                                           尖沙咀梳士巴利道
     评分                                                4.8
     评分人数                                             3693
     价格                                               3862
     价格等级                                                A
     热门等级                                                A
18   名字              香港文华东方酒店(Mandarin Oriental Hong Kong)
     类型                                               海滨风光
     城市                                                 香港
     地区                                                中西区
     地点                                           中环干诺道中5号
     评分                                                4.8
     评分人数                                             2452
     价格                                               3609
     价格等级                                                A
     热门等级                                                A
dtype: object

In [58]:
s.unstack()

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级,热门等级
116,香港四季酒店(Four Seasons Hotel Hong Kong),海滨风光,香港,中西区,中环 金融街8号,4.8,3461,12926,A,A
115,香港置地文华东方酒店(The Landmark Mandarin Oriental HK),休闲度假,香港,中西区,中环 皇后大道中15号置地广场,4.8,1285,4443,A,B
88,奕居(The Upper House),海滨风光,香港,中西区,金钟道88号太古广场,4.8,1369,4356,A,B
82,香港半岛酒店(The Peninsula Hong Kong),海滨风光,香港,油尖旺,尖沙咀梳士巴利道,4.8,3693,3862,A,A
18,香港文华东方酒店(Mandarin Oriental Hong Kong),海滨风光,香港,中西区,中环干诺道中5号,4.8,2452,3609,A,A

（11）纵向拆分数据集，分为df1和df2，df1包含名字，类型，城市，地区，df2包含名字，地点，评分，评分人数，价格，价格等级，热门等级。

In [60]:
s = "名字，地点，评分，评分人数，价格，价格等级，热门等级"
s.split("。")

['名字，地点，评分，评分人数，价格，价格等级，热门等级']

In [64]:
df1 = df[['名字','类型','城市','地区']]
df2 = df[['名字','地点','评分','评分人数','价格','价格等级','热门等级']]

（12）将df2按照价格进行排序，重新设置df2的索引。索引值等于价格排名。

In [66]:
df2 =df2.sort_values(by="价格",ascending=False)
df2.index = range(1,len(df2)+1)
df2

,名字,地点,评分,评分人数,价格,价格等级,热门等级
1,香港四季酒店(Four Seasons Hotel Hong Kong),中环 金融街8号,4.8,3461,12926,A,A
2,香港置地文华东方酒店(The Landmark Mandarin Oriental HK),中环 皇后大道中15号置地广场,4.8,1285,4443,A,B
3,奕居(The Upper House),金钟道88号太古广场,4.8,1369,4356,A,B
4,香港半岛酒店(The Peninsula Hong Kong),尖沙咀梳士巴利道,4.8,3693,3862,A,A
5,香港文华东方酒店(Mandarin Oriental Hong Kong),中环干诺道中5号,4.8,2452,3609,A,A
...,...,...,...,...,...,...,...
392,80后潘多拉旅馆(香港佐敦店)(原华丰宾馆)(Pandora After 80s Jordan),九龙佐敦佐敦道15号华丰大厦1字楼H室,3.1,36,70,C,C
393,香港加尔文青年旅舍(HK HOSTEL),佐敦道13-15号华丰大厦7楼A室,4.2,1480,70,C,B
394,香港日夜宾馆(Day and Night Hostel),"弥敦道36-44号重庆大厦10字楼D,E座D8& E2室",3.3,63,68,C,C
395,"巴黎旅馆(Paris Guest House (D2, 10/F))","Flat D2, 10/F, Block D, Chungking Mansion, 40 ...",2.0,5,67,C,C
396,香港经济型酒店 (家庭旅馆)(Hong Kong Budget Hostel),"弥敦道36-44号重庆大厦10字楼D,E座D8& E2室",2.0,29,67,C,C

（13）使用merge方法将df1和df2合并。

In [67]:
df3 = pd.merge(df1,df2,on="名字")
df3

,名字,类型,城市,地区,地点,评分,评分人数,价格,价格等级,热门等级
0,香港铜锣湾皇悦酒店(Empire Hotel Hong Kong-Causeway Bay),浪漫情侣,香港,东区,铜锣湾永兴街8号,4.5,12708,693,B,A
1,香港碧荟酒店(The BEACON),商务出行,香港,油尖旺,九龙旺角洗衣街88号,4.7,328,747,B,B
2,香港湾仔帝盛酒店(Dorsett Wanchai),浪漫情侣,香港,湾仔,皇后大道东387-397号,4.4,5014,693,B,A
3,如心艾朗酒店(L‘hotel elan),浪漫情侣,香港,观塘,观塘创业街38号,4.6,3427,581,B,A
4,香港隆堡柏宁顿酒店(Hotel Pennington by Rhombus),浪漫情侣,香港,湾仔,铜锣湾边宁顿街13-15号,4.5,1938,869,B,B
...,...,...,...,...,...,...,...,...,...,...
393,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45462,709,B,A
394,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45463,709,B,A
395,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45462,709,B,A
396,香港如心海景酒店暨会议中心(L‘hotel Nina et Convention Centre),海滨风光,香港,荃湾,荃湾 杨屋道8号,4.5,45463,709,B,A
397,香港花盈酒店(家庭旅馆)(Bloomy Hotel),地铁周边,香港,油尖旺,尖沙咀弥敦道87号华源大厦9字楼C2室,4.0,273,256,C,B

（14）将合并后的数据集保存数据到“酒店数据2.xlsx”。

In [ ]:
df2.to_excel("")